// Generated by CoffeeScript 1.6.3
(function() {
  var errorHandler;

  errorHandler = require('../lib');

  errorHandler.install();

  console.log("start");

  throw new Error("Something went wrong");

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
